apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ceph-homelab-tls
  namespace: rook-ceph
spec:
  secretName: ceph-homelab-tls
  ipAddresses:
    - 10.10.0.39
  dnsNames:
    - s3.home.lab
    - rook-ceph-rgw-homelab.rook-ceph.svc
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: homelab
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    # For production it is recommended to use more chunks, such as 4+2 or 8+4
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: false
  gateway:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 10.10.0.39
    sslCertificateRef: ceph-homelab-tls
    #port: 80
    securePort: 443
    instances: 1
  hosting:
    dnsNames:
      - "s3.home.lab"
