apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-home-lab
  namespace: harbor
spec:
  secretName: harbor-home-lab
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - homelab
      - jetstack
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - harbor.home.lab
  ipAddresses:
    - 10.0.0.33
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io