apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
  namespace: keycloak
spec:
  secretName: kc-home-lab-tls
  duration: 2160h #90d
  renewBefore: 360h #15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "kc.home.lab"
    - "keycloak"
  ipAddresses:
    - 10.10.0.32
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.0.32
  labels:
    app: keycloak
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8443
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:24.0.4
        resources:
          limits:
            memory: "768Mi"
            cpu: 800m
          requests:
            memory: "512Mi"
            cpu: 500m
        args: ["start"]
        volumeMounts:
        - name: certs
          mountPath: "/etc/certs"
          readOnly: true
        - name: truststore
          mountPath: "/etc/truststore"
          readOnly: true
        env:
        - name: KC_CACHE_STACK
          value: "kubernetes"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_HTTPS_PROTOCOLS
          value: TLSv1.2
        - name: KC_HOSTNAME_STRICET_BACKCHANNEL
          value: "false"
        - name: KC_PROXY
          value: "edge"
        - name: KC_LOG_LEVEL
          value: DEBUG
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_HTTPS_CERTIFICATE_FILE
          value: "/etc/certs/tls.crt"
        - name: KC_HTTPS_CERTIFICATE_KEY_FILE
          value: "/etc/certs/tls.key"
        - name: KC_HTTPS_TRUST_STORE_FILE
          value: "/etc/truststore/bundle.jks"
        - name: KC_HTTPS_TRUST_STORE_PASSWORD
          value: "changeit"
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_METRICS_ENABLED
          value: "false"
        - name: KC_HOSTNAME
          value: "kc.home.lab"
        - name: KC_HOSTNAME_DEBUG
          value: "true"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://keycloak-postgresql/postgres"
        - name: KC_DB_USERNAME
          value: "postgres"
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-postgresql
              key: postgres-password
        - name: KC_TRANSACTION_XA_ENABLED
          value: "true"
        - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
          value: "true"
        - name: CACHE_OWNERS_COUNT
          value: "2"
        - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
          value: "2"
        - name: jgroups.dns.query
          value: "headless-keycloak.keycloak.svc.cluster.local"
        - name: KC_FILE
          value: /opt/keycloak/data/import
        ports:
        - name: jgroups
          containerPort: 7600
        - name: https
          containerPort: 8443
        readinessProbe:
          initialDelaySeconds: 120
          periodSeconds: 1
          httpGet:
            scheme: HTTPS
            path: /health/ready
            port: 8443
      volumes:
      - name: certs
        secret:
          secretName: kc-home-lab-tls
      - name: truststore
        configMap:
          name: "home.lab"

          