apiVersion: v1
kind: Namespace
metadata:
  name: openldap
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap
  namespace: openldap
spec:
  secretName: openldap-tls-secret
  commonName: openldap.home.lab
  isCA: false
  usages:
    - server auth
    - client auth
  uris:
    - spiffe://cluster.local/ns/openldap/sa/openldap
  dnsNames:
    - openldap.openldap.svc.cluster.local
    - openldap.home.lab
    - openldap
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldif1
  namespace: openldap
data:
  01-default-users.ldif: |
    # home.lab
    dn: dc=home,dc=lab
    changetype: add
    objectClass: dcObject
    objectClass: organization
    dc: home
    o: k8s

    # users, home.lab
    dn: ou=users,dc=home,dc=lab
    changetype: add
    objectClass: organizationalUnit
    ou: users

    # user01, users, home.lab
    dn: cn=user01,ou=users,dc=home,dc=lab
    changetype: add
    cn: User1
    cn: user01
    sn: Bar1
    objectClass: inetOrgPerson
    objectClass: posixAccount
    objectClass: shadowAccount
    userPassword:: Yml0bmFtaTE=
    uid: user01
    uidNumber: 1000
    gidNumber: 1000
    homeDirectory: /home/user01

    # user02, users, home.lab
    dn: cn=user02,ou=users,dc=home,dc=lab
    changetype: add
    cn: User2
    cn: user02
    sn: Bar2
    objectClass: inetOrgPerson
    objectClass: posixAccount
    objectClass: shadowAccount
    userPassword:: Yml0bmFtaTI=
    uid: user02
    uidNumber: 1001
    gidNumber: 1001
    homeDirectory: /home/user02

    # user03, users, home.lab
    dn: cn=user03,ou=users,dc=home,dc=lab
    changetype: add
    cn: User3
    cn: user03
    sn: Bar3
    objectClass: inetOrgPerson
    objectClass: posixAccount
    objectClass: shadowAccount
    userPassword:: Yml0bmFtaTI=
    uid: user03
    uidNumber: 1002
    gidNumber: 1002
    homeDirectory: /home/user03

    # admins, users, home.lab
    dn: cn=admins,ou=users,dc=home,dc=lab
    changetype: add
    cn: admins
    objectClass: groupOfNames
    member: cn=user01,ou=users,dc=home,dc=lab
    
    # readers, users, home.lab
    dn: cn=readers,ou=users,dc=home,dc=lab
    changetype: add
    cn: readers
    objectClass: groupOfNames
    member: cn=user01,ou=users,dc=home,dc=lab
    member: cn=user02,ou=users,dc=home,dc=lab

    # readers, users, home.lab
    dn: cn=writers,ou=users,dc=home,dc=lab
    changetype: add
    cn: writers
    objectClass: groupOfNames
    member: cn=user03,ou=users,dc=home,dc=lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      volumes:
        - name: tls
          secret:
            secretName: openldap-tls-secret
        - name: ldif
          configMap:
            name: ldif1
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:latest
          #image: osixia/openldap:latest
          imagePullPolicy: "Always"
          env:
            - name: BITNAMI_DEBUG
              value: "true"
            - name: LDAP_ROOT
              value: dc=home,dc=lab
            - name: LDAP_ADMIN_DN
              value: cn=admin,dc=home,dc=lab
            - name: LDAP_SKIP_DEFAULT_TREE
              value: "yes"
            - name: LDAP_LOGLEVEL
              value: "1"
            - name: LDAP_ENABLE_TLS
              value: "no"
            - name: LDAP_TLS_CERT_FILE
              value: /etc/tls/tls.crt
            - name: LDAP_TLS_KEY_FILE
              value: /etc/tls/tls.key
            - name: LDAP_TLS_CA_FILE
              value: /etc/tls/ca.crt
          ports:
            - name: tcp-ldap
              containerPort: 1389
            - name: tcp-ldaps
              containerPort: 1636
          volumeMounts:
            - name: tls
              readOnly: true
              mountPath: "/etc/tls"
            - name: ldif
              mountPath: "/ldifs"
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: 1389
      targetPort: tcp-ldap
    - name: tcp-ldaps
      port: 1636
      targetPort: tcp-ldaps
  selector:
    app.kubernetes.io/name: openldap
---