---
apiVersion: k8s.streamnative.io/v1alpha1
kind: PulsarCoordinator
metadata:
  name: private-cloud
  namespace: pulsar
spec:
  #image: streamnative/private-cloud:3.0.0.4
  image: streamnative/private-cloud:3.0.1.2
  auditLog:
    categories:
      - Management
      - Describe
  istio:
    trustDomain: "home.lab"
  toolSet:
    enabled: true
    replicas: 1
---
apiVersion: zookeeper.streamnative.io/v1alpha1
kind: ZooKeeperCluster
metadata:
  name: zookeepers
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  #image: streamnative/private-cloud:3.0.0.4
  image: streamnative/private-cloud:3.0.1.2
  replicas: 3
  logConfig:
    level: INFO
    format: json
  pod:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
    jvmOptions:
      memoryOptions:
      - >
        -XX:MaxRAMPercentage=85
        -XX:+AlwaysPreTouch
        -Djute.maxbuffer=10485760
        -Dzookeeper.forceSync=no
      gcOptions:
      - >
        -XX:+UseZGC
        -XX:-ZUncommit
        -XX:+UseNUMA
        -XX:+UseDynamicNumberOfGCThreads
      gcLoggingOptions:
      - >
        -Xlog:gc*:file=/tmp/zk_gc.log::filecount=5,filesize=5m
      extraOptions:
      - >
        -XX:CompileThreshold=2000
        -XX:+PrintCompilation
    securityContext:
      runAsNonRoot: true
  persistence:
    reclaimPolicy: Delete
---
apiVersion: bookkeeper.streamnative.io/v1alpha1
kind: BookKeeperCluster
metadata:
  name: bookies
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  #image: streamnative/private-cloud:3.0.0.4
  image: streamnative/private-cloud:3.0.1.2
  replicas: 3
  zkServers: zookeepers-zk:2181
  logConfig:
    level: INFO
    format: json
  pod:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    jvmOptions:
      memoryOptions:
      - >
        -XX:MaxRAMPercentage=45
        -XX:+AlwaysPreTouch
        -Djute.maxbuffer=10485760
        -Dzookeeper.forceSync=no
      gcOptions:
      - >
        -XX:+UseZGC
        -XX:-ZUncommit
        -XX:+UseNUMA
        -XX:+UseDynamicNumberOfGCThreads
      gcLoggingOptions:
      - >
        -Xlog:gc*:file=/tmp/bk_gc.log::filecount=5,filesize=5m
      extraOptions:
      - >
        -XX:CompileThreshold=2000
        -XX:+PrintCompilation
    securityContext:
      runAsNonRoot: true
  storage:
    journal:
      numDirsPerVolume: 1
      numVolumes: 1
      volumeClaimTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
    ledger:
      numDirsPerVolume: 1
      numVolumes: 1
      volumeClaimTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 16Gi
    reclaimPolicy: Delete
---
apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarBroker
metadata:
  name: brokers
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  # apiObjects:
  #   externalService:
  #     managed: false
  #image: streamnative/private-cloud:3.0.0.4
  image: streamnative/private-cloud:3.0.1.2
  replicas: 3
  logConfig:
    level: INFO
    format: json
  zkServers: zookeepers-zk:2181
  dnsNames:
    - pulsar.home.lab
  pod:
    securityContext:
      runAsNonRoot: true
    jvmOptions:
      memoryOptions:
      - >
        -XX:MaxRAMPercentage=45
        -XX:+AlwaysPreTouch
        -Djute.maxbuffer=10485760
        -Dzookeeper.forceSync=no
      gcOptions:
      - >
        -XX:+UseZGC
        -XX:-ZUncommit
        -XX:+UseNUMA
        -XX:+UseDynamicNumberOfGCThreads
      gcLoggingOptions:
      - >
        -Xlog:gc*:file=/tmp/br_gc.log::filecount=5,filesize=5m
      extraOptions:
      - >
        -XX:CompileThreshold=2000
        -XX:+PrintCompilation
  config:
    pulsarRestMessagingServiceEnabled: true
    protocolHandlers:
      mop:
        enabled: true
        proxyEnabled: true
      aop:
        enabled: true
        proxyEnabled: true
      kop:
        enabled: true
  istio:
    authRules:
      fromSource:
        principals:
          - names
    enabled: true
    gateway:
      create: true
      selector: 
        istio: ingressgateway
      tls:
        certSecretName: pulsar-home-lab-tls
        mode: "simple"
    
    #trustDomain: "home.lab"
    mtls:
      mode: "PERMISSIVE"
  # logConfig:
  #   format: text
  #   level: DEBUG 
    #webSocketServiceEnabled: true
# ---
# apiVersion: pulsar.streamnative.io/v1alpha1
# kind: PulsarProxy
# metadata:
#   name: proxys
#   namespace: pulsar
# spec:
#   apiObjects:
#     externalService:
#       exposeSSLPort: true
#       managed: true
#       type: LoadBalancer
#       ports:
#       - name: pulsarssl
#         port: 6651
#         targetPort: 6651
#       - name: https
#         port: 443
#         targetPort: 8443
#       - name: websocket-tls
#         port: 9443
#         targetPort: 9443
#       - name: kop
#         port: 9092
#         targetPort: 9092
#       - name: aop-proxy
#         port: 5673
#         targetPort: 5673
#       - name: mop-proxy
#         port: 5682
#         targetPort: 5682
#   #image: streamnative/private-cloud:3.0.0.4
#   image: streamnative/private-cloud:3.0.1.2
#   replicas: 2
#   brokerAddress: brokers-broker
#   pod:
#     resources:
#       requests:
#         cpu: 200m
#         memory: 512Mi
#     jvmOptions:
#       memoryOptions:
#       - >
#         -XX:MaxRAMPercentage=45
#         -XX:+AlwaysPreTouch
#         -Djute.maxbuffer=10485760
#         -Dzookeeper.forceSync=no
#       gcOptions:
#       - >
#         -XX:+UseZGC
#         -XX:-ZUncommit
#         -XX:+UseNUMAls
#         -XX:+UseDynamicNumberOfGCThreads
#       gcLoggingOptions:
#       - >
#         -Xlog:gc*:file=/tmp/px_gc.log::filecount=5,filesize=5m
#       extraOptions:
#       - >
#         -XX:CompileThreshold=2000
#         -XX:+PrintCompilation
#     securityContext:
#       runAsNonRoot: true
#   dnsNames:
#     - s1.home.lab
#   webSocketServiceEnabled: true
#   configurationStoreServers: zookeepers-zk:2181
#   issuerRef:
#     group: cert-manager.io
#     kind: ClusterIssuer
#     name: ca-issuer
#   config:
#     # custom:
#     #   webSocketServiceEnabled: "true"
#     tls:
#       enabled: true
#   # logConfig:
#   #   level: DEBUG
# ---
# apiVersion: k8s.streamnative.io/v1alpha1
# kind: SNConsole
# metadata:
#   name: sn-private-console
#   namespace: pulsar
#   labels:
#     k8s.streamnative.io/coordinator-name: private-cloud
# spec:
#   image: streamnative/private-cloud-console:v2.0.0
#   kopServiceUrl: brokers-broker:9092
#   webServiceUrl: http://brokers-broker:8080
  # customization:
  #   match:
  #     name: 
  #   manifest:


# ---
# apiVersion: k8s.streamnative.io/v1alpha1
# kind: ApiKeys
# metadata:
#   labels:
#     cloud.streamnative.io/app: pulsar
#     cloud.streamnative.io/cluster: apikeys
#     cloud.streamnative.io/component: apikeys
#     cloud.streamnative.io/location: us-central1
#     cloud.streamnative.io/poolmember-name: gcp-shared-gcp-usce1-whale-snc
#     cloud.streamnative.io/poolmember-namespace: streamnative
#     cloud.streamnative.io/pulsar-cluster: apikeys
#     cloud.streamnative.io/pulsar-instance: apikeys
#     cloud.streamnative.io/role: apikeys
#     istio.io/rev: sn-stable
#     k8s.streamnative.io/coordinator-name: apikeys
#   name: apikeys
#   namespace: guangning
# spec:
#   brokerServiceUrl: 'pulsar://apikeys-broker.guangning.svc.cluster.local:6650'
#   config:
#     authenticator:
#       acceptedAudience: 'urn:sn:pulsar:guangning:apikeys'
#       enabled: true
#       issuers:
#         - 'https://auth.streamnative.cloud/'
#         - 'https://auth.sncloud-stg.dev/'
#         - 'https://auth.test.cloud.gcp.streamnative.dev/'
#     backend:
#       pulsarTopic: api_keys_api.example
#     server:
#       audience: 'urn:sn:pulsar:guangning:apikeys'
#       claimsToCopy:
#         - sub
#         - permissions
#         - aud
#         - scope
#         - 'https://streamnative.io/username'
#       currentKid: 7007ddf9-beac-4e74-8e32-f03453fea3e0
#   hostname: apikeys-49c084ec-dfaa-4aed-a879-68ae5c2d1b30.usce1-whale.test.g.sn2.dev
#   image: 'gcr.io/affable-ray-226821/streamnative/api-keys:sha-29e7517'
#   istio:
#     enabled: true
#     gateway:
#       gateways:
#         - apikeys-gateway
#   replicas: 1
---