apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: pulsar
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: pulsar-admin
  namespace: pulsar
spec:
  selector:
    matchLabels:
      app: pulsar
  jwtRules:
  - issuer: "https://kc.home.lab"
    jwksUri: https://kc.home.lab/.well-known/jwks.json
    audiences:
    - pulsar.home.lab
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: 
  namespace: foo
spec:
  selector:
    matchLabels:
      app: httpbin
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pulsar-gateway-certificate
  namespace: istio-system
spec:
  secretName: pulsar-home-lab-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - homelab
      - jetstack
  commonName: pulsar.home.lab
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - pulsar.home.lab
    - '*.pulsar.home.lab'
  ipAddresses:
    - 10.0.0.35
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: k8s.streamnative.io/v1alpha1
kind: PulsarCoordinator
metadata:
  name: private-cloud
  namespace: pulsar
spec:
  #image: streamnative/private-cloud:3.0.0.4
  image: streamnative/private-cloud:3.0.1.2
  # auditLog:
  #   categories:
  #     - Management
  #     - Describe
  toolSet:
    enabled: true
    replicas: 1
  istio:
    revision: sn-stable
    trustDomain: pulsar.home.lab
---
apiVersion: zookeeper.streamnative.io/v1alpha1
kind: ZooKeeperCluster
metadata:
  name: zookeepers
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  # customization:
  # - manifest: |
  #     spec: 
  #       template:
  #         spec:
  #           nodeSelector: 
  #             topology.kubernetes.io/zone: us-central1-a
  #           topologySpreadConstraints: null
  #   match:
  #     groupVersionKinds:
  #       - kind: StatefulSet
  #     name: .*-zk$
  #image: streamnative/private-cloud:3.0.0.4
  image: streamnative/private-cloud:3.0.1.2
  replicas: 3
  logConfig:
    format: json
    level: DEBUG
    # template: |
    #   Configuration:
    #     Appenders:
    #       Console:
    #         name: Console
    #         target: SYSTEM_OUT
    #         JSONLayout:
    #           eventEol: true
    #           compact: true
    #     Loggers:
    #       Root:
    #         level: debug
    #         AppenderRef:
    #           - ref: Console
  pod:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
    jvmOptions:
      memoryOptions:
      - >
        -XX:MaxRAMPercentage=85
        -XX:+AlwaysPreTouch
        -Djute.maxbuffer=10485760
        -Dzookeeper.forceSync=no
      gcOptions:
      - >
        -XX:+UseZGC
        -XX:-ZUncommit
        -XX:+UseNUMA
        -XX:+UseDynamicNumberOfGCThreads
      # gcLoggingOptions:
      # - >
      #   -Xlog:gc*:file=/tmp/zk_gc.log::filecount=5,filesize=5m
      # extraOptions:
      # - >
      #   -XX:CompileThreshold=2000
      #   -XX:+PrintCompilation
    securityContext:
      runAsNonRoot: true
  persistence:
    reclaimPolicy: Delete
---
apiVersion: bookkeeper.streamnative.io/v1alpha1
kind: BookKeeperCluster
metadata:
  name: bookies
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  #image: streamnative/private-cloud:3.0.0.4
  image: streamnative/private-cloud:3.0.1.2
  replicas: 3
  zkServers: zookeepers-zk:2181
  logConfig:
    format: json
    level: DEBUG
  pod:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    jvmOptions:
      memoryOptions:
      - >
        -XX:MaxRAMPercentage=45
        -XX:+AlwaysPreTouch
        -Djute.maxbuffer=10485760
        -Dzookeeper.forceSync=no
      gcOptions:
      - >
        -XX:+UseZGC
        -XX:-ZUncommit
        -XX:+UseNUMA
        -XX:+UseDynamicNumberOfGCThreads
      gcLoggingOptions:
      - >
        -Xlog:gc*:file=/tmp/bk_gc.log::filecount=5,filesize=5m
      extraOptions:
      - >
        -XX:CompileThreshold=2000
        -XX:+PrintCompilation
    securityContext:
      runAsNonRoot: true
  storage:
    journal:
      numDirsPerVolume: 1
      numVolumes: 1
      volumeClaimTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
    ledger:
      numDirsPerVolume: 1
      numVolumes: 1
      volumeClaimTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 16Gi
    reclaimPolicy: Delete
---
apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarBroker
metadata:
  name: brokers
  namespace: pulsar
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  # apiObjects:
  #   externalService:
  #     managed: false
  #image: streamnative/private-cloud:3.0.0.4
  image: streamnative/private-cloud:3.0.1.2
  replicas: 3
  logConfig:
    level: DEBUG
    format: json
  zkServers: zookeepers-zk:2181
  dnsNames:
    - pulsar.home.lab
  pod:
    securityContext:
      runAsNonRoot: true
    jvmOptions:
      memoryOptions:
      - >
        -XX:MaxRAMPercentage=45
        -XX:+AlwaysPreTouch
        -Djute.maxbuffer=10485760
        -Dzookeeper.forceSync=no
      gcOptions:
      - >
        -XX:+UseZGC
        -XX:-ZUncommit
        -XX:+UseNUMA
        -XX:+UseDynamicNumberOfGCThreads
      gcLoggingOptions:
      - >
        -Xlog:gc*:file=/tmp/br_gc.log::filecount=5,filesize=5m
      extraOptions:
      - >
        -XX:CompileThreshold=2000
        -XX:+PrintCompilation
  config:
    advertisedDomain: pulsar.home.lab
    serviceURLGenerationPolicy: FQDN
    pulsarRestMessagingServiceEnabled: true
    protocolHandlers:
      mop:
        enabled: true
        proxyEnabled: true
      aop:
        enabled: true
        proxyEnabled: true
      kop:
        enabled: true
  istio:
    enabled: true
    gateway:
      create: true
      selector: 
        istio: ingressgateway
      tls:
        certSecretName: pulsar-home-lab-tls
        mode: simple
    trustDomain: "pulsar.home.lab"

    #webSocketServiceEnabled: true
# ---
# apiVersion: pulsar.streamnative.io/v1alpha1
# kind: PulsarProxy
# metadata:
#   name: proxys
#   namespace: pulsar
# spec:
#   apiObjects:
#     externalService:
#       exposeSSLPort: true
#       managed: true
#       type: LoadBalancer
#       ports:
#       - name: pulsarssl
#         port: 6651
#         targetPort: 6651
#       - name: https
#         port: 443
#         targetPort: 8443
#       - name: websocket-tls
#         port: 9443
#         targetPort: 9443
#       - name: kop
#         port: 9092
#         targetPort: 9092
#       - name: aop-proxy
#         port: 5673
#         targetPort: 5673
#       - name: mop-proxy
#         port: 5682
#         targetPort: 5682
#   #image: streamnative/private-cloud:3.0.0.4
#   image: streamnative/private-cloud:3.0.1.2
#   replicas: 2
#   brokerAddress: brokers-broker
#   pod:
#     resources:
#       requests:
#         cpu: 200m
#         memory: 512Mi
#     jvmOptions:
#       memoryOptions:
#       - >
#         -XX:MaxRAMPercentage=45
#         -XX:+AlwaysPreTouch
#         -Djute.maxbuffer=10485760
#         -Dzookeeper.forceSync=no
#       gcOptions:
#       - >
#         -XX:+UseZGC
#         -XX:-ZUncommit
#         -XX:+UseNUMAls
#         -XX:+UseDynamicNumberOfGCThreads
#       gcLoggingOptions:
#       - >
#         -Xlog:gc*:file=/tmp/px_gc.log::filecount=5,filesize=5m
#       extraOptions:
#       - >
#         -XX:CompileThreshold=2000
#         -XX:+PrintCompilation
#     securityContext:
#       runAsNonRoot: true
#   dnsNames:
#     - s1.home.lab
#   webSocketServiceEnabled: true
#   configurationStoreServers: zookeepers-zk:2181
#   issuerRef:
#     group: cert-manager.io
#     kind: ClusterIssuer
#     name: ca-issuer
#   config:
#     # custom:
#     #   webSocketServiceEnabled: "true"
#     tls:
#       enabled: true
#   # logConfig:
#   #   level: DEBUG
# ---
# apiVersion: k8s.streamnative.io/v1alpha1
# kind: SNConsole
# metadata:
#   name: sn-private-console
#   namespace: pulsar
#   labels:
#     k8s.streamnative.io/coordinator-name: private-cloud
# spec:
#   image: streamnative/private-cloud-console:v2.0.0
#   kopServiceUrl: brokers-broker:9092
#   webServiceUrl: http://brokers-broker:8080
  # customization:
  #   match:
  #     name: 
  #   manifest:


# ---
# apiVersion: k8s.streamnative.io/v1alpha1
# kind: ApiKeys
# metadata:
#   labels:
#     cloud.streamnative.io/app: pulsar
#     cloud.streamnative.io/cluster: apikeys
#     cloud.streamnative.io/component: apikeys
#     cloud.streamnative.io/location: us-central1
#     cloud.streamnative.io/poolmember-name: gcp-shared-gcp-usce1-whale-snc
#     cloud.streamnative.io/poolmember-namespace: streamnative
#     cloud.streamnative.io/pulsar-cluster: apikeys
#     cloud.streamnative.io/pulsar-instance: apikeys
#     cloud.streamnative.io/role: apikeys
#     istio.io/rev: sn-stable
#     k8s.streamnative.io/coordinator-name: apikeys
#   name: apikeys
#   namespace: guangning
# spec:
#   brokerServiceUrl: 'pulsar://apikeys-broker.guangning.svc.cluster.local:6650'
#   config:
#     authenticator:
#       acceptedAudience: 'urn:sn:pulsar:guangning:apikeys'
#       enabled: true
#       issuers:
#         - 'https://auth.streamnative.cloud/'
#         - 'https://auth.sncloud-stg.dev/'
#         - 'https://auth.test.cloud.gcp.streamnative.dev/'
#     backend:
#       pulsarTopic: api_keys_api.example
#     server:
#       audience: 'urn:sn:pulsar:guangning:apikeys'
#       claimsToCopy:
#         - sub
#         - permissions
#         - aud
#         - scope
#         - 'https://streamnative.io/username'
#       currentKid: 7007ddf9-beac-4e74-8e32-f03453fea3e0
#   hostname: apikeys-49c084ec-dfaa-4aed-a879-68ae5c2d1b30.usce1-whale.test.g.sn2.dev
#   image: 'gcr.io/affable-ray-226821/streamnative/api-keys:sha-29e7517'
#   istio:
#     enabled: true
#     gateway:
#       gateways:
#         - apikeys-gateway
#   replicas: 1
---