apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: home.lab
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      name: "ca-secret"
      key: "tls.crt"
  target:
    configMap:
      key: "root-certs.pem"
    additionalFormats:
      jks:
        key: "bundle.jks"
      pkcs12:
        key: "bundle.p12"
      # secret:
      #   key: "ca.crt"              
    # namespaceSelector:
    #   matchLabels:
    #     cert-manager.io/trust-manager: trusted