- hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconf | default('/Users/ysung/.kube/config')}}"
  tasks:
  - name: create vault namespace
    kubernetes.core.k8s:
      name: vault
      api_version: v1
      kind: Namespace
      state: present
  - name: add hashicorp vault chart
    kubernetes.core.helm_repository:
      name: hashicorp
      repo_url: https://helm.releases.hashicorp.com
  - name: install vault
    kubernetes.core.helm:
      name: hashicorp-vault
      release_namespace: vault
      chart_ref: hashicorp/vault
      update_repo_cache: true