- hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconf | default('/Users/ysung/.kube/config')}}"
  tasks:
  - name: download rookceph
    tags: upgrade
    ansible.builtin.get_url:
      url: "{{ item.url }}"
      dest: "{{ item.dest }}"
      mode: '0664'
    loop:
      - url: https://raw.githubusercontent.com/rook/rook/release-{{ rook }}/deploy/examples/crds.yaml
        dest: /tmp/crds.yaml
      - url: https://raw.githubusercontent.com/rook/rook/release-{{ rook }}/deploy/examples/common.yaml
        dest: /tmp/common.yaml
      - url: https://raw.githubusercontent.com/rook/rook/release-{{ rook }}/deploy/examples/operator.yaml
        dest: /tmp/operator.yaml
  - name: create rook-ceph namespace
    kubernetes.core.k8s:
      name: rook-ceph
      api_version: v1
      kind: Namespace
      state: present
  - name: rook-ceph crd
    kubernetes.core.k8s:
      state: present
      src: "{{ item }}"
      # server_side_apply:
      #   force_conflicts: true
    tags: upgrade
    with_items:
      - /tmp/crds.yaml
      - /tmp/common.yaml
      - /tmp/operator.yaml
  - name: wait for ...
    ansible.builtin.wait_for:
      timeout: 30
  - name: rook-ceph cluster
    kubernetes.core.k8s:
      state: present
      src: ~/git/homelab/cluster.yaml
  - name: wait for ...
    ansible.builtin.wait_for:
      timeout: 30
  - name: rook-ceph block storage
    kubernetes.core.k8s:
      state: present
      src: ~/git/homelab/storageclass.yaml 
  - name: wait for ...
    ansible.builtin.wait_for:
      timeout: 30
  - name: set default storage class
    ansible.builtin.shell: |
      kubectl patch storageclass rook-ceph-block -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  - name: rook-ceph toolbox
    kubernetes.core.k8s:
      state: present
      src: ~/git/homelab/toolbox.yaml