- hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconf | default('/Users/ysung/.kube/config')}}"
  tasks:
  - name: download cert-manager
    ansible.builtin.get_url:
      url: https://github.com/cert-manager/cert-manager/releases/download/{{ certmanager_version }}/cert-manager.yaml
      dest: /tmp/cert-manager.yaml
      mode: '0644'
  - name: apply cert-manager
    kubernetes.core.k8s:
      state: present
      src: /tmp/cert-manager.yaml
  - name: create ca secret
    ansible.builtin.shell: |
      kubectl create secret tls ca-secret -n cert-manager --key={{ root_key }} --cert={{ root_crt }}
  - name: create cluster issuer
    kubernetes.core.k8s:
      state: present
      definition:    
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: ca-issuer
        spec:
          ca:
            secretName: ca-secret