- hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconf | default('/Users/ysung/.kube/config')}}"
  tasks:
  - name: operator-sdk
    ansible.builtin.shell: |
      operator-sdk olm install
    ignore_errors: true
  - name: download argocd operator
    ansible.builtin.get_url:
      url: https://operatorhub.io/install/argocd-operator.yaml
      dest: /tmp/argocd-operator.yaml
      mode: '0664'
  - name: apply argocd operator
    kubernetes.core.k8s:
      state: present
      src: /tmp/argocd-operator.yaml 
  - name: wait for operator
    ansible.builtin.wait_for:
      timeout: 30
  - name: apply argocd cr
    kubernetes.core.k8s:
      state: present
      src: "{{ argocd | default('/Users/ysung/git/homelab/argocd.yaml')}}"
  - name: argo rollout
    ansible.builtin.shell: |
      kubectl create namespace argo-rollouts
      kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml