- hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconf | default('/Users/ysung/.kube/config')}}"
  tasks:
  - name: create keycloak namespace
    kubernetes.core.k8s:
      name: keycloak
      api_version: v1
      kind: Namespace
      definition:
        metadata:
          labels:
            cert-manager.io/trust-manager: "trusted"
      state: present

  - name: add bitnami chart
    kubernetes.core.helm_repository:
      name: bitnami
      repo_url: https://charts.bitnami.com/bitnami
    ignore_errors: true
  - name: install postgresql
    kubernetes.core.helm:
      name: keycloak
      release_namespace: keycloak
      chart_ref: bitnami/postgresql
      update_repo_cache: true
  - name: apply keycloak deploy
    kubernetes.core.k8s:
      state: present
      src: "{{ keycloak | default('/Users/ysung/git/homelab/keycloak.yaml')}}"  