- hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconf | default('/Users/ysung/.kube/config')}}"
  tasks:
  - name: create elastic namespace
    kubernetes.core.k8s:
      name: elastic
      api_version: v1
      kind: Namespace
      state: present
  - name: download elastic operator
    ansible.builtin.get_url:
      url: "{{ item.url }}"
      dest: "/tmp/{{ item.name }}"
      mode: '0664'
    with_items:
      - { name: elastic-crds.yaml, url: https://download.elastic.co/downloads/eck/2.13.0/crds.yaml }
      - { name: elastic-operator.yaml, url: https://download.elastic.co/downloads/eck/2.13.0/operator.yaml }
  - name: apply elastic operator
    kubernetes.core.k8s:
      state: present
      src: /tmp/elastic-operator.yaml
    with_items:
      - /tmp/elastic-crds.yaml
      - /tmp/elastic-operator.yaml
  #wait for 30s
  # - name: apply elastic cr
  #   kubernetes.core.k8s:
  #     state: present
  #     src: "{{ elastic | default('/Users/ysung/git/homelab/elastic.yaml')}}"  
