kubectl create -f https://operatorhub.io/install/elastic-cloud-eck.yaml
kubectl create ns elastic
kubectl create -f - <<EOF
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-certificate
  namespace: elastic
spec:
  secretName: s3-home-lab-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - homelab
      - jetstack
  commonName: s1.home.lab
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - s3.home.lab
    - '*s3.home.lab'
  uris:
    - spiffe://cluster.local/ns/istio-system/ingressgateway/pulsar
  ipAddresses:
    - 10.0.0.33
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
EOF

kubectl create -f - <<EOF
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: my-ec
  namespace: elastic
spec:
  version: 8.6.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
EOF

kubectl apply -f - <<EOF
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: my-kibana
  namespace: elastic
spec:
  version: 8.6.2
  count: 1
  elasticsearchRef:
    name: my-ec
    namespace: elastic
  http:
    tls:
      certificate:
        secretName: s3-home-lab-tls
    service:
      spec:
        type: LoadBalancer
        externalName: s3.home.lab
EOF