- hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconf | default('/Users/ysung/.kube/config')}}"
  tasks:
  - name: create elastic namespace
    kubernetes.core.k8s:
      name: elastic
      api_version: v1
      kind: Namespace
      state: present
  - name: download elastic operator
    ansible.builtin.get_url:
      url: https://operatorhub.io/install/elastic-cloud-eck.yaml
      dest: /tmp/elastic-operator.yaml
      mode: '0664'
  - name: apply elastic operator
    kubernetes.core.k8s:
      state: present
      src: /tmp/elastic-operator.yaml
  #wait for 30s
  - name: apply elastic cr
    kubernetes.core.k8s:
      state: present
      src: "{{ elastic | default('/Users/ysung/git/homelab/elastic.yaml')}}"  