- hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconf | default('/Users/ysung/.kube/config')}}"
  tasks:
  - name: create fluent namespace
    kubernetes.core.k8s:
      name: fluent
      api_version: v1
      kind: Namespace
      state: present
  - name: download fluent operator
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/fluent/fluent-operator/release-2.1/manifests/setup/setup.yaml
      dest: /tmp/fluent-operator.yaml
      mode: '0664'
  - name: apply fluent operator
    kubernetes.core.k8s:
      state: present
      src: /tmp/fluent-operator.yaml
