- hosts: master
  gather_facts: yes
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - name: copy kubeadmin config
    ansible.builtin.copy:
      src: /Users/ysung/git/homelab/kubeadm.yaml
      dest: /tmp/kubeadm.yaml
  - name: kubeadm init
    ansible.builtin.command: |
      kubeadm init --config /tmp/kubeadm.yaml
  - name: kube admin config
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: "{{ kubeconf | default('/Users/ysung/.kube/config') }}"
      flat: yes
- hosts: workers
  gather_facts: no
  become: yes
  tags: join
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - name: load nbd rbd
    shell: "modprobe {{ item }}"
    with_items:
    - "nbd"
    - "rbd"
  - name: generate join token
    shell: kubeadm token create --print-join-command
    register: join_command
    delegate_to: m1.home.lab
  - set_fact:
      kubeadm_join: "{{ join_command.stdout }}"
  - name: kubeadm join
    shell: "{{ kubeadm_join }}"
- hosts: localhost
  gather_facts: no
  tasks:
  - name: wait for webhook
    ansible.builtin.wait_for:
      timeout: 60
  - name: patch dataplane
    ansible.builtin.shell: |
      for i in `k get csr --no-headers| awk '{print $1}'`; do k certificate approve $i; done
      kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml