- hosts: master
  gather_facts: yes
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - name: add ca pair
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
    loop:
      - { src: '/Users/ysung/git/homelab/root.key', dest: '/etc/kubernetes/pki/ca.key', mode: '0600' }
      - { src: '/Users/ysung/git/homelab/root.crt', dest: '/etc/kubernetes/pki/ca.crt', mode: '0644' }
  - name: copy kubeadmin config
    ansible.builtin.copy:
      src: /Users/ysung/git/homelab/kubeadm.yaml
      dest: /tmp/kubeadm.yaml
  - name: kubeadm init
    ansible.builtin.command: |
      kubeadm init --config /tmp/kubeadm.yaml
  - name: kube admin config
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: "{{ kubeconf | default('/Users/ysung/.kube/config') }}"
      flat: yes
- hosts: workers
  gather_facts: no
  become: yes
  tags: join
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - name: load nbd rbd
    shell: "modprobe {{ item }}"
    with_items:
    - "nbd"
    - "rbd"
  - name: generate join token
    shell: kubeadm token create --print-join-command
    register: join_command
    delegate_to: m1.home.lab
  - set_fact:
      kubeadm_join: "{{ join_command.stdout }}"
  - name: kubeadm join
    shell: "{{ kubeadm_join }}"
- hosts: localhost
  gather_facts: no
  tasks:
  - name: patch dataplane
    ansible.builtin.shell: | 
      kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  - name: wait for webhook
    ansible.builtin.wait_for:
      timeout: 30
  - name: patch dataplane
    ansible.builtin.shell: |    
      for i in `k get csr --no-headers| awk '{print $1}'`; do k certificate approve $i; done
- hosts: all
  gather_facts: yes
  become: yes
  tags: kube-bench
  tasks:
  - name: 4.1-1
    ansible.builtin.file:
      path: "{{ item }}"
      owner: root
      group: root
      mode: '600'
    with_items:
      # - "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
      - "/var/lib/kubelet/config.yaml"
  - name: 4.1-2
    ansible.builtin.file:
      path: "{{ item }}"
      owner: root
      group: root
      mode: '644'
    with_items:
      - "/etc/kubernetes/pki/ca.crt"
  - name: restart
    ansible.builtin.systemd_service:
      name: kubelet
      state: restarted
      daemon_reload: true