- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: kubeadm reset
    shell: 'kubeadm reset -f'
  - name: stop kubelet and containerd
    systemd:
      name: "{{ item }}"
      state: stopped
    with_items:
    - containerd
    - kubelet
  - name: remove cni and rook
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
    - /etc/cni/net.d/
    - /var/lib/rook/
    - /var/lib/kubelet/plugins
    - /var/lib/kubelet/plugins_registry
- hosts: master,nuc9.home.lab
  gather_facts: no
  become: yes
  tasks:
  - name: teardown ssd blk
    shell: |
      blkdiscard {{ item }} -f
      partprobe {{ item }}
    with_items:
    - /dev/mapper/vgubuntu-rook
  - name: remove disk lock
    shell: |
      ls /dev/mapper/ceph-* | xargs -I% -- dmsetup remove_all --force %
      rm -rf /dev/ceph-* /dev/mapper/ceph--* /dev/rbd*
- hosts: w[1-4].home.lab,p3.home.lab
  gather_facts: no
  become: yes
  tasks:
  - name: teardown ssd blk
    shell: |
      blkdiscard {{ item }} -f
      partprobe {{ item }}
    with_items:
    - /dev/mapper/ubuntu--vg-rook
  - name: remove disk lock
    shell: |
      ls /dev/mapper/ceph-* | xargs -I% -- dmsetup remove_all --force %
      rm -rf /dev/ceph-* /dev/mapper/ceph--* /dev/rbd*
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: unload nbd rbd
    shell: "modprobe -r {{ item }}"
    with_items:
    - "nbd"
  - name: restart start containerd
    systemd:
      name: "{{ item }}"
      state: started
    with_items:
    - containerd
