- hosts: master
  gather_facts: no
  become: yes
  serial: 1
  ignore_unreachable: true
  tasks:
  - name: install new kube packages
    shell: apt-get install -y --allow-change-held-packages --allow-downgrades kubeadm="{{ k8s_version }}-00" kubelet="{{ k8s_version }}-00" kubectl="{{ k8s_version }}-00"
  - name: hold k8s
    dpkg_selections:
      name: "{{ item }}"
      selection: hold
    with_items:
    - kubelet
    - kubeadm
    - kubectl
  - name: upgrade kubeadm
    shell: kubeadm upgrade apply v{{ k8s_version }} -y

  - name: localaction-drain {{ inventory_hostname }}
    become: false
    local_action: ansible.builtin.command kubectl drain {{ inventory_hostname }} --ignore-daemonsets
  - name: restart kubelet
    systemd:
      name: kubelet
      state: restarted
      daemon_reload: yes
  - name: localaction-uncordon {{ inventory_hostname }}
    become: false
    local_action: ansible.builtin.command kubectl uncordon {{ inventory_hostname }}
- hosts: workers
  gather_facts: no
  become: yes
  serial: 1
  ignore_unreachable: true
  tasks:
  - name: install new kube packages
    shell: apt-get install -y --allow-change-held-packages --allow-downgrades kubeadm="{{ k8s_version }}-00" kubectl="{{ k8s_version }}-00" kubelet="{{ k8s_version }}-00"
  - name: upgrade kubeadm
    shell: kubeadm upgrade node
  - name: localaction-drain {{ inventory_hostname }}
    become: false
    local_action: ansible.builtin.command kubectl drain {{ inventory_hostname }} --ignore-daemonsets --delete-emptydir-data --disable-eviction
  - name: restart kubelet
    systemd:
      name: kubelet
      state: restarted
      daemon_reload: yes
  - name: localaction-uncordon {{ inventory_hostname }}
    become: false
    local_action: ansible.builtin.command kubectl uncordon {{ inventory_hostname }}